spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # 하위 서비스들이 등록된다!!
        - id: service1-route
          uri: lb://SERVER-1
          # URL 기술, 다양한 방식 등록, 메소드,.....
          predicates:
            - Path=/service1/**

        - id: service1-route
          uri: lb://SERVER-2
              # URL 기술, 다양한 방식 등록, 메소드,.....
          predicates:
            - Path=/service2/**

        #- id:



# 게이트웨이 담당, 모든 유저(혹은 프런트엔드)는 이 포트로 접속 -> 8080
server:
  port: 8080

# 유레카 서버의 서비스 정보 페이지 등록
eureka:
  client:
    service-url:
      # 현재는 미구현 상태로 404임
      defaultZone: http://localhost:8761/eureka
